site_name:  Project
repo_url: https://github.com/CarlosEduardoFSouza/project
repo_name: Project
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png 

markdown_extensions:
  - attr_list

extra_css:
  - stylesheet/extra.css